[package]
name = "rusty-mail-server"
description = "An email server, written in Rust"
repository = "https://github.com/MarkGhebrial/rusty-mail-server"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["pop3", "database"]

[dependencies]
tokio = { version = "1", features = ["full"] }
pop3 = { path = "pop3" }
database = { path = "database" }
toml = "0.5.9"
serde = "1.0.144"
#tokio-native-tls = "0.3.0"