[package]
name = "rusty-mail-server"
description = "An email server, written in Rust"
repository = "https://github.com/MarkGhebrial/rusty-mail-server"
license = "MIT"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["pop3", "mailbox"]

[dependencies]
pop3 = { path = "pop3" }
mailbox = { path = "mailbox" }