# Filepath for Log4rs config (relative to working directory). Omit field
# to use same directory as the executable.
log_4rs_config = "log4rs.yaml"

[database]
# Postgres username
user = "mail"
# Postgres password
password = "Login123" 

[[domains]]
name = "localhost"
users = [
    "mghebrial",
    "limy"
]
tls_settings = "disabled"