# Filepath for Log4rs config (relative to working directory). Omit field
# to use same directory as the executable.
log_4rs_config = "log4rs.yaml"

[database]
url = "sqlite:./sqlite.db?mode=rwc"

[[domains]]
name = "localhost"
users = [
    "mghebrial",
    "limy"
]
tls_settings = "disabled"