# Filepath for Log4rs config (relative to working directory). Omit field
# to use same directory as the executable.
log_4rs_config = "log4rs.yaml"

bind_address = "0.0.0.0"

[database]
url = "sqlite:./sqlite.db?mode=rwc"

[[domains]]
name = "localhost"
users = [
    "mghebrial",
    "limy"
]
tls_settings = "disabled"

[[domains]]
name = "ghebrial.net"
selector = "mail" # The thing that goes in front of the actual email domain. The "mail_server1" part of "mail_server1.ghebrial.net"
users = [
    "mark",
    "darth.mark",
    "supermark"
]
tls_settings = "disabled"